version: "3.9"

networks:
  spark-network:
    driver: bridge
    name: spark-network

services:
  spark-master:
    container_name: spark-master
    # image: bitnami/spark:3.3.0            # master budujemy z czystego image
    build:
      context: ./dockerfiles
      dockerfile: ./master.dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8082:8080'
      - '7077:7077'
    networks:
      - spark-network


  spark-worker-1:
    container_name: spark-worker-1
    build:
      context: ./dockerfiles
      dockerfile: ./worker.dockerfile
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - spark-network
    ports:
      - '8083:8080'
      - '7078:7077'
#    volumes: #  dodajmy woluminy gdzie będziemy zapisywać wyniki ze sparka
#      - ${HOME}/kessenger/spark-volumes:/opt/work-dir


  spark-worker-2:
    container_name: spark-worker-2
    build:
      context: ./dockerfiles
      dockerfile: ./worker.dockerfile
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - spark-network
    ports:
      - '8084:8080'
      - '7079:7077'

#  spark-submitter:
#    container_name: spark-submitter
#    build:
#      context: ./dockerfiles
#      dockerfile: ./driver-program.dockerfile
#    depends_on:
#      # - spark-master
#      - spark-worker-1
#      - spark-worker-2
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark-master:7077
#      - SPARK_WORKER_MEMORY=1G
#      - SPARK_WORKER_CORES=2
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#    networks:
#      - spark-network
#    ports:
#      - '8085:8080'
#      - '7080:7077'
##    volumes: #  dodajmy woluminy gdzie będziemy zapisywać wyniki ze sparka
##      - ${HOME}/kessenger/spark-volumes:/opt/work-dir
