#!/bin/zsh

chmod +x generateJAR

do_not_build=false

for arr in $@ ; do

  if [[ $arr = "--restartAll" ]] ; then
    echo "Restarting Spark App."
    echo "Removing Docker container."

    docker stop spark-submitter
    docker rm -v spark-submitter
    docker rmi spr-clsr-test-env_spark-submitter

    docker stop spark-worker-2
    docker rm -v spark-worker-2
    docker rmi spr-clsr-test-env_spark-worker-2

    docker stop spark-worker-1
    docker rm -v spark-worker-1
    docker rmi spr-clsr-test-env_spark-worker-1

    docker stop spark-master
    docker rm -v spark-master
    docker rmi spr-clsr-test-env_spark-master
  fi

  if [[ $arr = "--restart" ]] ; then
      echo "Restarting Spark App."
      echo "Removing Docker container."

      docker stop spark-submitter
      docker rm -v spark-submitter
      docker rmi spr-clsr-test-env_spark-submitter

      fi

  if [[ $arr = "--do-not-build" ]] ; then
    do_not_build=true
  fi

done

if [[ $do_not_build = false ]] ; then
  echo "Removing Binaries."
  rm -rf ./target/scala-2.12/
  ./generateJAR
  # rm -rf $HOME/spr-clsr-test-env/logs/application.log
fi

cp log4j2.xml ./dockerfiles/log4j2.xml

cp ./target/scala-2.12/spr-clsr-test-env-0.1.0.jar ./dockerfiles/spr-clsr-test-env-0.1.0.jar


docker-compose up -d # --build

rm -rf ./dockerfiles/log4j2.xml
rm -rf ./dockerfiles/spr-clsr-test-env-0.1.0.jar